<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2021-12-02 10:52:07 --> Severity: error --> Exception: Call to undefined function pg_connect() C:\wamp1\www\epikp\system\database\drivers\postgre\postgre_driver.php 154
ERROR - 2021-12-02 10:52:07 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of Error given, called in C:\wamp1\www\epikp\system\core\Common.php on line 662 and defined in C:\wamp1\www\epikp\system\core\Exceptions.php:190
Stack trace:
#0 C:\wamp1\www\epikp\system\core\Common.php(662): CI_Exceptions->show_exception(Object(Error))
#1 [internal function]: _exception_handler(Object(Error))
#2 {main}
  thrown C:\wamp1\www\epikp\system\core\Exceptions.php 190
ERROR - 2021-12-02 11:10:13 --> Severity: error --> Exception: Call to undefined function pg_connect() C:\wamp1\www\epikp\system\database\drivers\postgre\postgre_driver.php 154
ERROR - 2021-12-02 11:10:13 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of Error given, called in C:\wamp1\www\epikp\system\core\Common.php on line 662 and defined in C:\wamp1\www\epikp\system\core\Exceptions.php:190
Stack trace:
#0 C:\wamp1\www\epikp\system\core\Common.php(662): CI_Exceptions->show_exception(Object(Error))
#1 [internal function]: _exception_handler(Object(Error))
#2 {main}
  thrown C:\wamp1\www\epikp\system\core\Exceptions.php 190
ERROR - 2021-12-02 11:14:42 --> Severity: error --> Exception: Call to undefined function pg_connect() C:\wamp1\www\epikp\system\database\drivers\postgre\postgre_driver.php 154
ERROR - 2021-12-02 11:14:42 --> Severity: Error --> Uncaught TypeError: Argument 1 passed to CI_Exceptions::show_exception() must be an instance of Exception, instance of Error given, called in C:\wamp1\www\epikp\system\core\Common.php on line 662 and defined in C:\wamp1\www\epikp\system\core\Exceptions.php:190
Stack trace:
#0 C:\wamp1\www\epikp\system\core\Common.php(662): CI_Exceptions->show_exception(Object(Error))
#1 [internal function]: _exception_handler(Object(Error))
#2 {main}
  thrown C:\wamp1\www\epikp\system\core\Exceptions.php 190
